package com.cervalid.platform.academic.profile.enums;

public enum AcademicProgram {

    DISENO_DESARROLLO_SOFTWARE,
    ARQUITECTURA_SISTEMAS_INFORMACION,

    ADMINISTRACION_EMPRESAS,
    ADMINISTRACION_RECURSOS_HUMANOS,
    ADMINISTRACION_NEGOCIOS_INTERNACIONALES,

    CONTABILIDAD,
    ADMINISTRACION_BANCARIA_FINANCIERA,

    DISEÑO_GRAFICO_PUBLICIDAD
}